### ISSUE TITLE
a problem in visualization.py

### ISSUE THREAD

**Issue by mouthful** [shervinea/enzynet#2]
Hi, 
When I run your script 'visualization.py', there is an error:
```
Traceback (most recent call last):
  File "visualization.py", line 183, in <module>
    visualize_pdb('2Q3Z', p=0, v_size=32, weights=None)
  File "visualization.py", line 42, in visualize_pdb
    plot_volume(volume, pdb_id, v_size, num, weights=weights)
  File "visualization.py", line 68, in plot_volume
    plot_matrix(ax, volume)
  File "visualization.py", line 151, in plot_matrix
    plot_cube_at(pos=(i-0.5,j-0.5,k-0.5), ax=ax)
  File "visualization.py", line 136, in plot_cube_at
    ax.plot_surface(X, Y, Z, color='g', rstride=1, cstride=1, alpha=1)
  File "/home/xxxx/anaconda3/envs/enzyme/lib/python3.7/site-packages/mpl_toolkits/mplot3d/axes3d.py", line 1610, in plot_surface
    if Z.ndim != 2:
AttributeError: 'list' object has no attribute 'ndim'
```
I think it is caused by the type of variables `X`,`Y`and`Z`, cuz their attributes don't contain **'ndim'**. I fixed this issue by changing their type from list to  np.array.

**Comment by mohaiminul2810** [comment]
I am facing the same issue. May I know where you have changed the code and how?
I am new in this so having a tough time to solve it.

**Comment by mohaiminul2810** [comment]
I am new in this. Could not solve the following error. Can you help me on this?
```
Using TensorFlow backend.
Traceback (most recent call last):
  File "enzynet/visualization.py", line 183, in <module>
    visualize_pdb('2Q3Z', p=0, v_size=32, weights=None)
  File "enzynet/visualization.py", line 41, in visualize_pdb
    plot_volume(volume, pdb_id, v_size, num, weights=weights)
  File "enzynet/visualization.py", line 109, in plot_volume
    str(weights) + '_' + str(num) + '.pdf')
  File "/usr/lib/python3/dist-packages/matplotlib/pyplot.py", line 701, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/matplotlib/figure.py", line 1834, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/usr/lib/python3/dist-packages/matplotlib/backend_bases.py", line 2267, in print_figure
    **kwargs)
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_pdf.py", line 2584, in print_pdf
    file = PdfFile(filename, metadata=kwargs.pop("metadata", None))
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_pdf.py", line 439, in __init__
    fh = open(filename, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: '../scripts/volume/2Q3Z_32_None_1.pdf'
```

**Comment by tariksalay** [comment]
working on it
